sudo: required
services:
  - docker

before_install:
  - docker build -t anhtuhsp/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true anhtuhsp/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react-practice"
  env: "DockerReactPractice-env"
  bucket_name: "elasticbeanstalk-us-east-1-392410360729"
  bucket_path: "docker-react-practice"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"